<?php
declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use App\Services\RulesCacheService;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        if (!Schema::hasTable('ref_archetypeblueprints')) {
            Schema::create('ref_archetypeblueprints', function (Blueprint $table) {
                $table->increments('ID');
                $table->string('Name', 100);
                $table->string('Slug', 50)->unique();
                $table->string('Description', 255)->nullable();
                $table->string('ArmorCategory', 20)->default('medium'); // none, light, medium, heavy
                $table->string('PreferredArmor', 100)->nullable();
                $table->string('ShieldCategory', 20)->default('none'); // none, buckler, light, heavy, tower
                $table->string('PreferredShield', 100)->nullable();
                $table->string('PrimaryWeaponCategory', 50)->default('sword'); // sword, axe, mace_hammer, spear_polearm, finesse, ranged, staff_club, monk_weapon, unarmed, simple, any
                $table->string('PreferredPrimaryWeapon', 100)->nullable();
                $table->string('SecondaryWeapon', 100)->nullable();
                $table->string('PreferredRangedWeapon', 100)->nullable();
                $table->string('Ammunition', 100)->nullable();
                $table->string('ImplementCategory', 50)->nullable(); // holy_symbol, druidic_focus, wand, staff, rod, dorje, psicrown, none
                $table->string('ConsumableTypes', 255)->nullable(); // comma-separated list
                $table->string('AccessorySlots', 255)->nullable(); // comma-separated prioritized slots
                $table->string('ClassConfigIDs', 255)->nullable(); // comma-separated list of matching ref_classconfigs IDs
            });
        }

        // Seed comprehensive archetype blueprints
        $blueprints = [
            [
                'ID' => 1,
                'Name' => 'Sword Fighter / Swordsman',
                'Slug' => 'sword_fighter',
                'Description' => 'Heavy martial frontline fighter specializing in longswords, heavy shields, and plated armor.',
                'ArmorCategory' => 'heavy',
                'PreferredArmor' => 'Full plate',
                'ShieldCategory' => 'heavy',
                'PreferredShield' => 'Shield, heavy steel',
                'PrimaryWeaponCategory' => 'sword',
                'PreferredPrimaryWeapon' => 'Sword, long-',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Bow, composite long-',
                'Ammunition' => 'Arrow, sheaf (20)',
                'ImplementCategory' => null,
                'ConsumableTypes' => 'healing_potion,buff_potion',
                'AccessorySlots' => 'waist,shoulders,ring,neck',
                'ClassConfigIDs' => '9,46,60,91,102',
            ],
            [
                'ID' => 2,
                'Name' => 'Axe Fighter / Axeman',
                'Slug' => 'axe_fighter',
                'Description' => 'Vigorous warrior wielding brutal battleaxes and greataxes in heavy mail or plate.',
                'ArmorCategory' => 'heavy',
                'PreferredArmor' => 'Full plate',
                'ShieldCategory' => 'heavy',
                'PreferredShield' => 'Shield, heavy steel',
                'PrimaryWeaponCategory' => 'axe',
                'PreferredPrimaryWeapon' => 'Axe, battle-',
                'SecondaryWeapon' => 'Handaxe',
                'PreferredRangedWeapon' => 'Bow, composite long-',
                'Ammunition' => 'Arrow, sheaf (20)',
                'ImplementCategory' => null,
                'ConsumableTypes' => 'healing_potion,buff_potion',
                'AccessorySlots' => 'waist,shoulders,ring,neck',
                'ClassConfigIDs' => '85,88',
            ],
            [
                'ID' => 3,
                'Name' => 'Mace Fighter / Hammerman',
                'Slug' => 'mace_fighter',
                'Description' => 'Heavy crushing specialist brandishing warhammers, heavy maces, and morningstars.',
                'ArmorCategory' => 'heavy',
                'PreferredArmor' => 'Full plate',
                'ShieldCategory' => 'heavy',
                'PreferredShield' => 'Shield, heavy steel',
                'PrimaryWeaponCategory' => 'mace_hammer',
                'PreferredPrimaryWeapon' => 'Hammer, war-',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Crossbow, heavy',
                'Ammunition' => 'Bolt, heavy (10)',
                'ImplementCategory' => null,
                'ConsumableTypes' => 'healing_potion,buff_potion',
                'AccessorySlots' => 'waist,shoulders,ring,neck',
                'ClassConfigIDs' => '86,89',
            ],
            [
                'ID' => 4,
                'Name' => 'Spear Fighter / Spearman',
                'Slug' => 'spear_fighter',
                'Description' => 'Formation warrior and skirmisher wielding spears, polearms, and halberds.',
                'ArmorCategory' => 'heavy',
                'PreferredArmor' => 'Banded mail',
                'ShieldCategory' => 'light',
                'PreferredShield' => 'Shield, light steel',
                'PrimaryWeaponCategory' => 'spear_polearm',
                'PreferredPrimaryWeapon' => 'Spear',
                'SecondaryWeapon' => 'Sword, short-',
                'PreferredRangedWeapon' => 'Crossbow, heavy',
                'Ammunition' => 'Bolt, heavy (10)',
                'ImplementCategory' => null,
                'ConsumableTypes' => 'healing_potion,buff_potion',
                'AccessorySlots' => 'waist,shoulders,ring,neck',
                'ClassConfigIDs' => '87,90',
            ],
            [
                'ID' => 5,
                'Name' => 'Cavalryman / Knight',
                'Slug' => 'cavalry_knight',
                'Description' => 'Mounted champion equipped with full plate, heavy lance, longsword, and heavy shield.',
                'ArmorCategory' => 'heavy',
                'PreferredArmor' => 'Full plate',
                'ShieldCategory' => 'heavy',
                'PreferredShield' => 'Shield, heavy steel',
                'PrimaryWeaponCategory' => 'spear_polearm',
                'PreferredPrimaryWeapon' => 'Lance, heavy',
                'SecondaryWeapon' => 'Sword, long-',
                'PreferredRangedWeapon' => 'Bow, composite short-',
                'Ammunition' => 'Arrow, sheaf (20)',
                'ImplementCategory' => null,
                'ConsumableTypes' => 'healing_potion,buff_potion',
                'AccessorySlots' => 'waist,shoulders,ring,neck',
                'ClassConfigIDs' => '',
            ],
            [
                'ID' => 6,
                'Name' => 'Barbarian / Berserker',
                'Slug' => 'barbarian',
                'Description' => 'Ferocious tribal warrior wielding a massive greataxe or greatsword in medium armor.',
                'ArmorCategory' => 'medium',
                'PreferredArmor' => 'Breastplate',
                'ShieldCategory' => 'none',
                'PreferredShield' => null,
                'PrimaryWeaponCategory' => 'axe',
                'PreferredPrimaryWeapon' => 'Greataxe',
                'SecondaryWeapon' => 'Handaxe',
                'PreferredRangedWeapon' => 'Bow, composite short-',
                'Ammunition' => 'Arrow, sheaf (20)',
                'ImplementCategory' => null,
                'ConsumableTypes' => 'healing_potion,buff_potion',
                'AccessorySlots' => 'waist,shoulders,neck,feet',
                'ClassConfigIDs' => '10',
            ],
            [
                'ID' => 7,
                'Name' => 'Duelist / Swashbuckler',
                'Slug' => 'duelist',
                'Description' => 'Agile, stylish combatant fighting with rapiers, bucklers, and main-gauche daggers.',
                'ArmorCategory' => 'light',
                'PreferredArmor' => 'Studded leather',
                'ShieldCategory' => 'buckler',
                'PreferredShield' => 'Buckler',
                'PrimaryWeaponCategory' => 'finesse',
                'PreferredPrimaryWeapon' => 'Rapier',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Crossbow, light',
                'Ammunition' => 'Bolt, light (10)',
                'ImplementCategory' => null,
                'ConsumableTypes' => 'healing_potion,buff_potion',
                'AccessorySlots' => 'feet,ring,shoulders,hands',
                'ClassConfigIDs' => '11',
            ],
            [
                'ID' => 8,
                'Name' => 'Archer / Ranger',
                'Slug' => 'archery_ranger',
                'Description' => 'Deadeye wilderness scout and sniper with composite bows and light armor.',
                'ArmorCategory' => 'light',
                'PreferredArmor' => 'Studded leather',
                'ShieldCategory' => 'none',
                'PreferredShield' => null,
                'PrimaryWeaponCategory' => 'ranged',
                'PreferredPrimaryWeapon' => 'Bow, composite long-',
                'SecondaryWeapon' => 'Sword, short-',
                'PreferredRangedWeapon' => 'Bow, composite long-',
                'Ammunition' => 'Arrow, sheaf (20)',
                'ImplementCategory' => null,
                'ConsumableTypes' => 'healing_potion,buff_potion',
                'AccessorySlots' => 'feet,shoulders,hands,ring',
                'ClassConfigIDs' => '20,21,47,68',
            ],
            [
                'ID' => 9,
                'Name' => 'Rogue / Scout / Assassin',
                'Slug' => 'rogue_scout',
                'Description' => 'Stealthy infiltrator using daggers, shortswords, light crossbows, and thieves tools.',
                'ArmorCategory' => 'light',
                'PreferredArmor' => 'Leather armor',
                'ShieldCategory' => 'none',
                'PreferredShield' => null,
                'PrimaryWeaponCategory' => 'finesse',
                'PreferredPrimaryWeapon' => 'Sword, short-',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Crossbow, light',
                'Ammunition' => 'Bolt, light (10)',
                'ImplementCategory' => null,
                'ConsumableTypes' => 'healing_potion,buff_potion',
                'AccessorySlots' => 'feet,hands,ring,waist',
                'ClassConfigIDs' => '22,48,49,50,64',
            ],
            [
                'ID' => 10,
                'Name' => 'Cleric of Life / Healer',
                'Slug' => 'cleric_life',
                'Description' => 'Devout priest clothed in medium armor with wooden shield, heavy mace, and silver holy symbol.',
                'ArmorCategory' => 'medium',
                'PreferredArmor' => 'Breastplate',
                'ShieldCategory' => 'heavy',
                'PreferredShield' => 'Shield, heavy wooden',
                'PrimaryWeaponCategory' => 'mace_hammer',
                'PreferredPrimaryWeapon' => 'Mace, heavy',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Crossbow, light',
                'Ammunition' => 'Bolt, light (10)',
                'ImplementCategory' => 'holy_symbol',
                'ConsumableTypes' => 'healing_potion,scroll_divine,buff_potion',
                'AccessorySlots' => 'neck,shoulders,ring,waist',
                'ClassConfigIDs' => '4',
            ],
            [
                'ID' => 11,
                'Name' => 'Cleric of War / Crusader',
                'Slug' => 'cleric_war',
                'Description' => 'Battle priest in full plate armor with steel shield, warhammer or flail, and war holy symbol.',
                'ArmorCategory' => 'heavy',
                'PreferredArmor' => 'Full plate',
                'ShieldCategory' => 'heavy',
                'PreferredShield' => 'Shield, heavy steel',
                'PrimaryWeaponCategory' => 'mace_hammer',
                'PreferredPrimaryWeapon' => 'Hammer, war-',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Crossbow, heavy',
                'Ammunition' => 'Bolt, heavy (10)',
                'ImplementCategory' => 'holy_symbol',
                'ConsumableTypes' => 'healing_potion,buff_potion,scroll_divine',
                'AccessorySlots' => 'neck,shoulders,ring,waist',
                'ClassConfigIDs' => '5,7',
            ],
            [
                'ID' => 12,
                'Name' => 'Cleric of Knowledge / Scholar Priest',
                'Slug' => 'cleric_knowledge',
                'Description' => 'Scholarly divine investigator in medium armor with light shield, mace, and spell scrolls.',
                'ArmorCategory' => 'medium',
                'PreferredArmor' => 'Scale mail',
                'ShieldCategory' => 'light',
                'PreferredShield' => 'Shield, light wooden',
                'PrimaryWeaponCategory' => 'mace_hammer',
                'PreferredPrimaryWeapon' => 'Mace, light',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Crossbow, light',
                'Ammunition' => 'Bolt, light (10)',
                'ImplementCategory' => 'holy_symbol',
                'ConsumableTypes' => 'healing_potion,scroll_divine',
                'AccessorySlots' => 'head,neck,ring,shoulders',
                'ClassConfigIDs' => '6',
            ],
            [
                'ID' => 13,
                'Name' => 'Druid / Nature Warden',
                'Slug' => 'druid',
                'Description' => 'Protector of the wild wearing non-metallic hide armor with wooden shield, scimitar, and mistletoe.',
                'ArmorCategory' => 'light',
                'PreferredArmor' => 'Hide armor',
                'ShieldCategory' => 'heavy',
                'PreferredShield' => 'Shield, heavy wooden',
                'PrimaryWeaponCategory' => 'sword',
                'PreferredPrimaryWeapon' => 'Scimitar',
                'SecondaryWeapon' => 'Sickle',
                'PreferredRangedWeapon' => 'Sling',
                'Ammunition' => 'Bullet, sling (10)',
                'ImplementCategory' => 'druidic_focus',
                'ConsumableTypes' => 'healing_potion,scroll_divine,buff_potion',
                'AccessorySlots' => 'neck,shoulders,ring,waist',
                'ClassConfigIDs' => '8',
            ],
            [
                'ID' => 14,
                'Name' => 'Witch Doctor / Shaman / Adept',
                'Slug' => 'witch_doctor',
                'Description' => 'Mystic tribal practitioner in hide/leather with ritual staff, fetish focus, and brews.',
                'ArmorCategory' => 'light',
                'PreferredArmor' => 'Leather armor',
                'ShieldCategory' => 'none',
                'PreferredShield' => null,
                'PrimaryWeaponCategory' => 'staff_club',
                'PreferredPrimaryWeapon' => 'Quarterstaff',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Sling',
                'Ammunition' => 'Bullet, sling (10)',
                'ImplementCategory' => 'druidic_focus',
                'ConsumableTypes' => 'healing_potion,buff_potion,scroll_divine',
                'AccessorySlots' => 'neck,head,ring,hands',
                'ClassConfigIDs' => '43,44,45',
            ],
            [
                'ID' => 15,
                'Name' => 'Battlemage / War Wizard',
                'Slug' => 'battlemage',
                'Description' => 'Martial spellcaster in chain shirt or enchanted bracers with longsword, wand, and combat spells.',
                'ArmorCategory' => 'light',
                'PreferredArmor' => 'Chain shirt',
                'ShieldCategory' => 'none',
                'PreferredShield' => null,
                'PrimaryWeaponCategory' => 'sword',
                'PreferredPrimaryWeapon' => 'Sword, long-',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Crossbow, light',
                'Ammunition' => 'Bolt, light (10)',
                'ImplementCategory' => 'wand',
                'ConsumableTypes' => 'healing_potion,scroll_arcane,buff_potion',
                'AccessorySlots' => 'arms,ring,shoulders,head',
                'ClassConfigIDs' => '51,52',
            ],
            [
                'ID' => 16,
                'Name' => 'Arcane Caster (Wizard / Sorcerer)',
                'Slug' => 'arcane_caster',
                'Description' => 'Scholarly or intuitive arcane caster in wizard robes with quarterstaff, wand, and spell scrolls.',
                'ArmorCategory' => 'none',
                'PreferredArmor' => "Monk's Robes",
                'ShieldCategory' => 'none',
                'PreferredShield' => null,
                'PrimaryWeaponCategory' => 'staff_club',
                'PreferredPrimaryWeapon' => 'Quarterstaff',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Crossbow, light',
                'Ammunition' => 'Bolt, light (10)',
                'ImplementCategory' => 'wand',
                'ConsumableTypes' => 'healing_potion,scroll_arcane',
                'AccessorySlots' => 'head,ring,shoulders,neck',
                'ClassConfigIDs' => '23,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,101',
            ],
            [
                'ID' => 17,
                'Name' => 'Psionic Manifester (Psion)',
                'Slug' => 'psionic_manifester',
                'Description' => 'Disciplined mind manifesting psychic powers in comfortable attire with staff, dorje, and power stones.',
                'ArmorCategory' => 'none',
                'PreferredArmor' => "Monk's Robes",
                'ShieldCategory' => 'none',
                'PreferredShield' => null,
                'PrimaryWeaponCategory' => 'staff_club',
                'PreferredPrimaryWeapon' => 'Quarterstaff',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Crossbow, light',
                'Ammunition' => 'Bolt, light (10)',
                'ImplementCategory' => 'dorje',
                'ConsumableTypes' => 'healing_potion,power_stone',
                'AccessorySlots' => 'head,ring,shoulders,waist',
                'ClassConfigIDs' => '13,14,15,16,17,18,99',
            ],
            [
                'ID' => 18,
                'Name' => 'Psychic Warrior / Mind Blade',
                'Slug' => 'psiwarrior',
                'Description' => 'Psionic martial powerhouse clad in heavy armor with greatsword, composite bow, and power stones.',
                'ArmorCategory' => 'heavy',
                'PreferredArmor' => 'Full plate',
                'ShieldCategory' => 'heavy',
                'PreferredShield' => 'Shield, heavy steel',
                'PrimaryWeaponCategory' => 'sword',
                'PreferredPrimaryWeapon' => 'Sword, great-',
                'SecondaryWeapon' => 'Sword, short-',
                'PreferredRangedWeapon' => 'Bow, composite long-',
                'Ammunition' => 'Arrow, sheaf (20)',
                'ImplementCategory' => 'dorje',
                'ConsumableTypes' => 'healing_potion,power_stone,buff_potion',
                'AccessorySlots' => 'waist,shoulders,ring,neck',
                'ClassConfigIDs' => '19,100',
            ],
            [
                'ID' => 19,
                'Name' => 'Monk / Martial Artist',
                'Slug' => 'unarmed_monk',
                'Description' => 'Ascetic martial artist fighting unarmored with monk weapons, sling, and defensive bracers.',
                'ArmorCategory' => 'none',
                'PreferredArmor' => "Monk's Robes",
                'ShieldCategory' => 'none',
                'PreferredShield' => null,
                'PrimaryWeaponCategory' => 'monk_weapon',
                'PreferredPrimaryWeapon' => 'Quarterstaff',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Sling',
                'Ammunition' => 'Bullet, sling (10)',
                'ImplementCategory' => null,
                'ConsumableTypes' => 'healing_potion,buff_potion',
                'AccessorySlots' => 'arms,feet,ring,waist',
                'ClassConfigIDs' => '12,92,93,94,95,96',
            ],
            [
                'ID' => 20,
                'Name' => 'Templar / Holy Knight',
                'Slug' => 'templar',
                'Description' => 'Righteous holy knight in full plate with heavy shield, longsword, holy symbol, and war mount gear.',
                'ArmorCategory' => 'heavy',
                'PreferredArmor' => 'Full plate',
                'ShieldCategory' => 'heavy',
                'PreferredShield' => 'Shield, heavy steel',
                'PrimaryWeaponCategory' => 'sword',
                'PreferredPrimaryWeapon' => 'Sword, long-',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Bow, composite long-',
                'Ammunition' => 'Arrow, sheaf (20)',
                'ImplementCategory' => 'holy_symbol',
                'ConsumableTypes' => 'healing_potion,buff_potion,scroll_divine',
                'AccessorySlots' => 'neck,shoulders,ring,waist',
                'ClassConfigIDs' => '24,25,26,27',
            ],
            [
                'ID' => 21,
                'Name' => 'Savage / Giant Berserker',
                'Slug' => 'savage_berserker',
                'Description' => 'Raw barbarian fighter in hides wielding enormous greataxes and heavy clubs.',
                'ArmorCategory' => 'medium',
                'PreferredArmor' => 'Hide armor',
                'ShieldCategory' => 'none',
                'PreferredShield' => null,
                'PrimaryWeaponCategory' => 'axe',
                'PreferredPrimaryWeapon' => 'Greataxe',
                'SecondaryWeapon' => 'Club',
                'PreferredRangedWeapon' => 'Bow, composite short-',
                'Ammunition' => 'Arrow, sheaf (20)',
                'ImplementCategory' => null,
                'ConsumableTypes' => 'healing_potion,buff_potion',
                'AccessorySlots' => 'waist,neck,shoulders',
                'ClassConfigIDs' => '61,97,98',
            ],
            [
                'ID' => 22,
                'Name' => 'Gladiator',
                'Slug' => 'gladiator',
                'Description' => 'Arena fighter wielding tridents, nets, exotic blades, and medium chainmail.',
                'ArmorCategory' => 'medium',
                'PreferredArmor' => 'Chainmail',
                'ShieldCategory' => 'heavy',
                'PreferredShield' => 'Shield, heavy steel',
                'PrimaryWeaponCategory' => 'spear_polearm',
                'PreferredPrimaryWeapon' => 'Trident',
                'SecondaryWeapon' => 'Sword, short-',
                'PreferredRangedWeapon' => 'Javelin',
                'Ammunition' => null,
                'ImplementCategory' => null,
                'ConsumableTypes' => 'healing_potion,buff_potion',
                'AccessorySlots' => 'arms,waist,shoulders',
                'ClassConfigIDs' => '65',
            ],
            [
                'ID' => 23,
                'Name' => 'Aristocrat / Diplomat',
                'Slug' => 'aristocrat',
                'Description' => 'Highborn noble or diplomat in padded silk attire with fine rapier and buckler.',
                'ArmorCategory' => 'light',
                'PreferredArmor' => 'Padded armor',
                'ShieldCategory' => 'buckler',
                'PreferredShield' => 'Buckler',
                'PrimaryWeaponCategory' => 'finesse',
                'PreferredPrimaryWeapon' => 'Rapier',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Crossbow, hand',
                'Ammunition' => 'Bolt, hand (10)',
                'ImplementCategory' => null,
                'ConsumableTypes' => 'healing_potion',
                'AccessorySlots' => 'ring,neck,shoulders',
                'ClassConfigIDs' => '1,2,3,53,54',
            ],
            [
                'ID' => 24,
                'Name' => 'Commoner / Laborer / Craftsman',
                'Slug' => 'commoner',
                'Description' => 'Townsfolk, artisan, or farmer wearing everyday clothing with work club, dagger, and sling.',
                'ArmorCategory' => 'none',
                'PreferredArmor' => 'Fine clothing',
                'ShieldCategory' => 'none',
                'PreferredShield' => null,
                'PrimaryWeaponCategory' => 'simple',
                'PreferredPrimaryWeapon' => 'Club',
                'SecondaryWeapon' => 'Dagger',
                'PreferredRangedWeapon' => 'Sling',
                'Ammunition' => 'Bullet, sling (10)',
                'ImplementCategory' => null,
                'ConsumableTypes' => 'healing_potion',
                'AccessorySlots' => 'waist,feet',
                'ClassConfigIDs' => '55,56,57,58,59',
            ],
        ];

        DB::table('ref_archetypeblueprints')->upsert($blueprints, ['ID'], [
            'Name', 'Slug', 'Description', 'ArmorCategory', 'PreferredArmor', 'ShieldCategory',
            'PreferredShield', 'PrimaryWeaponCategory', 'PreferredPrimaryWeapon', 'SecondaryWeapon',
            'PreferredRangedWeapon', 'Ammunition', 'ImplementCategory', 'ConsumableTypes',
            'AccessorySlots', 'ClassConfigIDs'
        ]);

        RulesCacheService::warm();
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('ref_archetypeblueprints');
        RulesCacheService::warm();
    }
};
