<?php
declare(strict_types=1);

namespace Tests\Unit;

use Tests\TestCase;
use App\Services\Entity\EntityEngine;
use App\Services\Entity\EquipmentManager;
use App\Services\Entity\TraitEvaluator;
use App\Services\Entity\ModifierStackingEngine;

class CharacterViewerAndEnginePolishTest extends TestCase
{
    public function testArmorRegistersDrDeCAndEC(): void
    {
        $engine = new ModifierStackingEngine();
        $context = ['lvl' => 1];

        // Armor trait
        $traits = TraitEvaluator::parse('Armor { Category=ArmHv; DR=8; DeC=-2; EC=4; }');
        TraitEvaluator::applyTraitsToEngine($traits, $engine, $context, 'Full plate', 'wearer');

        $this->assertEquals(8, $engine->getTotal('DR'));
        $this->assertEquals(-2, $engine->getTotal('DeC'));
        $this->assertEquals(4, $engine->getTotal('EC'));
    }

    public function testSpeedFormattingWithClimbAndSwimMultipliers(): void
    {
        $entity = [
            'Name' => 'Lizardfolk Champion',
            'BaseRace' => 1,
            'Classes' => [4],
            'BaseStr' => 14,
            'BaseDex' => 12,
            'BaseCon' => 14,
            'BaseInt' => 10,
            'BaseWis' => 10,
            'BaseCha' => 10,
        ];

        $calc = EntityEngine::calculate($entity);
        $this->assertArrayHasKey('speeds', $calc);
        $this->assertArrayHasKey('display', $calc['speeds']);
        $this->assertStringContainsString('sq Ground', $calc['speeds']['display']);
        $this->assertStringContainsString('Climb ×', $calc['speeds']['display']);
        $this->assertStringNotContainsString('Climb', $calc['traits']['movement_str'] ?? '');
    }

    public function testEquippedAndCarriedWeaponsIncluded(): void
    {
        $entity = [
            'Name' => 'Armed Warrior',
            'BaseRace' => 1,
            'Classes' => [4],
            'BaseStr' => 16,
            'BaseDex' => 12,
            'BaseCon' => 14,
            'BaseInt' => 10,
            'BaseWis' => 10,
            'BaseCha' => 10,
            'Possessions' => [
                [
                    'ID' => 88, // Longsword
                    'Name' => 'Sword, long-',
                    'location' => EquipmentManager::LOCATION_EQUIPPED,
                ],
                [
                    'ID' => 104, // Bow
                    'Name' => 'Bow, composite long-',
                    'location' => EquipmentManager::LOCATION_CARRIED,
                ],
                [
                    'ID' => 387, // Horse (Stowed)
                    'Name' => 'Horse, light war-',
                    'location' => EquipmentManager::LOCATION_STOWED,
                ]
            ]
        ];

        $calc = EntityEngine::calculate($entity);
        $weaponNames = array_column($calc['attacks']['weapons'] ?? [], 'name');
        
        $this->assertContains('Sword, long-', $weaponNames);
        $this->assertContains('Bow, composite long-', $weaponNames);
        $this->assertNotContains('Horse, light war-', $weaponNames);
    }

    public function testFormatItemTraitsDescription(): void
    {
        $armorTrait = 'Armor { Category=ArmHv; DR=8; DeC=-2; EC=4; } Material { Steel; }';
        $formatted = EntityEngine::formatItemTraitsDescription($armorTrait);
        
        $this->assertStringContainsString('DR 8', $formatted);
        $this->assertStringContainsString('DeC -2', $formatted);
        $this->assertStringContainsString('EC 4', $formatted);
        $this->assertStringContainsString('Heavy Armor', $formatted);
    }

    public function testShieldsAreIncludedInEquippedWeaponsAndAkimboNotAutoGenerated(): void
    {
        $entity = [
            'Name' => 'Knight with Sword and Shield',
            'BaseRace' => 1,
            'Classes' => [4],
            'BaseStr' => 18,
            'BaseDex' => 12,
            'BaseCon' => 16,
            'BaseInt' => 10,
            'BaseWis' => 10,
            'BaseCha' => 10,
            'Possessions' => [
                [
                    'ID' => 88, // Longsword
                    'Name' => 'Sword, long-',
                    'location' => EquipmentManager::LOCATION_EQUIPPED,
                ],
                [
                    'ID' => 571, // Heavy Steel Shield (Subtype 9)
                    'Name' => 'Shield, heavy steel',
                    'location' => EquipmentManager::LOCATION_EQUIPPED,
                ],
                [
                    'ID' => 104, // Bow
                    'Name' => 'Bow, composite long-',
                    'location' => EquipmentManager::LOCATION_EQUIPPED,
                ],
                [
                    'ID' => 152, // Arrows (Subtype 8)
                    'Name' => 'Arrows (20)',
                    'Subtype' => 8,
                    'location' => EquipmentManager::LOCATION_EQUIPPED,
                ],
                [
                    'ID' => 170, // Full plate (Subtype 13)
                    'Name' => 'Full plate',
                    'Subtype' => 13,
                    'location' => EquipmentManager::LOCATION_EQUIPPED,
                ],
            ]
        ];

        $calc = EntityEngine::calculate($entity);
        $weaponNames = array_column($calc['attacks']['weapons'] ?? [], 'name');

        // Shields (Subtype 9) MUST be included in weapons & attacks
        $this->assertContains('Shield, heavy steel', $weaponNames);
        $this->assertContains('Sword, long-', $weaponNames);
        $this->assertContains('Bow, composite long-', $weaponNames);

        // Ammunition and non-weaponized armor MUST be excluded
        $this->assertNotContains('Arrows (20)', $weaponNames);
        $this->assertNotContains('Full plate', $weaponNames);

        // Akimbo attacks MUST NOT be created automatically
        $this->assertEmpty($calc['attacks']['akimbo']);
    }

    public function testWeaponDamageFormulaParsing(): void
    {
        $abilityMods = ['Str' => 4, 'Dex' => 2];

        // 1. Melee with StrMod and Slashing damage
        $parsed1H = EntityEngine::parseWeaponDamageFormula('d10+StrMod S', $abilityMods, 3, 0, false);
        $this->assertEquals('1d10+7 S', $parsed1H['display']);
        $this->assertEquals(12.5, $parsed1H['avg_damage']);
        $this->assertEquals('S', $parsed1H['damage_type']);

        $parsed2H = EntityEngine::parseWeaponDamageFormula('d10+StrMod S', $abilityMods, 3, 0, true);
        $this->assertEquals('1d10+9 S', $parsed2H['display']);
        $this->assertEquals(14.5, $parsed2H['avg_damage']);

        // 2. Shield bash with Bludgeoning damage
        $parsedShield = EntityEngine::parseWeaponDamageFormula('d4+StrMod B', $abilityMods, 2, 0, false);
        $this->assertEquals('1d4+6 B', $parsedShield['display']);
        $this->assertEquals(8.5, $parsedShield['avg_damage']);
        $this->assertEquals('B', $parsedShield['damage_type']);

        // 3. Multi-die weapon e.g. Greatsword 2d8+StrMod S
        $parsedGreatsword = EntityEngine::parseWeaponDamageFormula('2d8+StrMod S', $abilityMods, 4, 0, true);
        $this->assertEquals('2d8+10 S', $parsedGreatsword['display']);
        $this->assertEquals(19.0, $parsedGreatsword['avg_damage']);

        // 4. Flat bonus in composite bows e.g. +4
        $parsedFlat = EntityEngine::parseWeaponDamageFormula('+4', $abilityMods, 0, 0, false);
        $this->assertEquals('+4', $parsedFlat['display']);
        $this->assertEquals(4.0, $parsedFlat['avg_damage']);
        $this->assertTrue($parsedFlat['is_flat_mod'] ?? false);

        // 5. Special damage strings
        $parsedEntangle = EntityEngine::parseWeaponDamageFormula('Entangle', $abilityMods, 0, 0, false);
        $this->assertEquals('Entangle', $parsedEntangle['display']);
    }

    public function testProjectileWeaponAmmunitionIntegration(): void
    {
        $entity = [
            'Name' => 'ObarionHigh Archer',
            'BaseRace' => 12,
            'Classes' => [4],
            'BaseStr' => 18,
            'BaseDex' => 16,
            'BaseCon' => 16,
            'BaseInt' => 10,
            'BaseWis' => 13,
            'BaseCha' => 17,
            'Skills' => [
                31 => 14.0, // Weapons - Bows: 14 ranks
                25 => 14.0, // Weapons - Heavy Blades: 14 ranks
                28 => 14.0, // Weapons - Shields: 14 ranks
            ],
            'Equipment' => [
                ['ID' => 104, 'Name' => 'Bow, composite long- (Str 18)', 'location' => EquipmentManager::LOCATION_EQUIPPED],
                ['ID' => 88, 'Name' => 'Sword, long-', 'location' => EquipmentManager::LOCATION_EQUIPPED],
                ['ID' => 571, 'Name' => 'Shield, heavy steel', 'location' => EquipmentManager::LOCATION_EQUIPPED],
                ['ID' => 113, 'Name' => 'Arrow, flight (20)', 'Qty' => 2, 'location' => EquipmentManager::LOCATION_CARRIED],
            ],
        ];

        $calc = EntityEngine::calculate($entity);
        $weapons = $calc['attacks']['weapons'] ?? [];

        // 1. Verify Bow is detected as projectile weapon
        $this->assertArrayHasKey(104, $weapons);
        $bow = $weapons[104];
        $this->assertTrue($bow['is_projectile']);
        $this->assertEquals('Arrow', $bow['ammo_required']);
        $this->assertNotEmpty($bow['compatible_ammo']);

        // 2. Verify compatible ammo types are populated
        $ammoNames = array_column($bow['compatible_ammo'], 'name');
        $this->assertContains('Arrow, flight (20)', $ammoNames);
        $this->assertContains('Arrow, sheaf (20)', $ammoNames);
        $this->assertContains('Arrow, cutter (10)', $ammoNames);

        // 3. Verify carried ammo is flagged in inventory
        $flightAmmo = collect($bow['compatible_ammo'])->firstWhere('name', 'Arrow, flight (20)');
        $this->assertNotNull($flightAmmo);
        $this->assertTrue($flightAmmo['in_inventory']);
        $this->assertEquals(2, $flightAmmo['inventory_qty']);
        $this->assertEquals('32 m', $flightAmmo['range']); // Flight arrow 16m + bow 16m = 32m

        // 4. Verify Longsword and Shield damage
        $sword = $weapons[88];
        $this->assertStringContainsString('1d10', $sword['one_handed']['damage']);
        $this->assertStringContainsString('S', $sword['one_handed']['damage']);

        $shield = $weapons[571];
        $this->assertStringContainsString('1d4', $shield['one_handed']['damage']);
        $this->assertStringContainsString('B', $shield['one_handed']['damage']);
    }
}
